export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  FETCH_ERROR: "FETCH_ERROR",

  CACHE_ERROR: "CACHE_ERROR",

  SUPABASE_ERROR: "SUPABASE_ERROR",

  SUPABASE_AUTH_ERROR: "SUPABASE_AUTH_ERROR",

  AGGREGATOR_ERROR: "AGGREGATOR_ERROR",

  SOURCE_UNAVAILABLE: "SOURCE_UNAVAILABLE",
};
